#!/usr/bin/env bash
#script that will display information about subdomains.
information () {
    record=$(dig "$2"."$1" +short)
    type=$(dig "$2"."$1" +noall +answer | awk '{print $4}')
    echo "The subdomain $2 is a $type record and points to $record"
}

if [ "$#" -lt 2 ]
then
    information $1 "www"
    information $1 "lb-01"
    information $1 "web-01"
    information $1 "web-02"
elif [ "$#" -eq 2 ]
then
    information $1 $2
fi
