#!/usr/bin/env bash
#it configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\nlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n'
service nginx restart
