#!/usr/bin/env bash
#it configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt update
sudo apt install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sed -i '/server_name _;/a \\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html/;\n\t}\n' /etc/nginx/sites-available/default
service nginx restart
