#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algo

# Update the system
sudo apt-get update -y

# Install HAProxy
sudo apt-get install -y haproxy

# Enable HAProxy to be started by the init script
sudo systemctl enable haproxy

# Create a backup of the original haproxy.cfg file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Define the configuration
echo "
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 1200-web-01 35.153.194.5:80 check
   server 1200-web-02 52.91.144.169:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
