#!/usr/bin/env bash
#configures a new Ubuntu machine to respect above requirements
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy=2.0.\*
echo "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\nbackend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 407460-web-01 35.153.194.5:80 check\n\tserver 407460-web-02 52.91.144.169:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
